CI: Add full test support
The patch adds support for running full tests in the local CI
Environment. New features added:

- New target `ci-full` which runs the full test. This is also the
  default now
- Renamed the previous target `ci-smokeit` to `ci-smoke`
- Unlike previous if the available memory is more than 16G a default of
  8G will be used
- Removed some unnecessary debug messages
- Added `dummybuf` kernel module to the list of modules to be loaded on
  the VM

The features that can be tested:
`make TARGET=<TARGET> TARGET_ARCH=<TARGET_ARCH> CITYPE=full ci`
`make TARGET=<TARGET> TARGET_ARCH=<TARGET_ARCH> ci` is also the same as
above as CITYPE full is the default now

Approved by:	lwhsu
Sponsored by:	The FreeBSD Foundation
Differential Revision:	https://reviews.freebsd.org/D48015

diff --git a/tests/ci/tools/freebsdci b/tests/ci/tools/freebsdci
--- a/tests/ci/tools/freebsdci
+++ b/tests/ci/tools/freebsdci
@@ -26,6 +26,7 @@
 . /etc/rc.subr
 
 : ${freebsdci_enable:="NO"}
+: ${freebsdci_type:="full"}
 
 name="freebsdci"
 desc="Run FreeBSD CI"
@@ -33,10 +34,13 @@ rcvar=freebsdci_enable
 start_cmd="firstboot_ci_run"
 stop_cmd=":"
 os_arch=$(uname -p)
+tardev=/dev/vtbd1
+metadir=/meta
+istar=$(file -s ${tardev} | grep "POSIX tar archive" | wc -l)
 
 auto_shutdown()
 {
-	# XXX: Currently RISC-V kernels lack the ability to
+	# NOTE: Currently RISC-V kernels lack the ability to
 	#      make qemu exit on shutdown. Reboot instead;
 	#      it makes qemu exit too.
 	case "$os_arch" in
@@ -53,8 +57,6 @@ smoke_tests()
 {
 	echo
 	echo "--------------------------------------------------------------"
-	echo "BUILD sequence COMPLETED"
-	echo "IMAGE sequence COMPLETED"
 	echo "BOOT sequence COMPLETED"
 	echo "INITIATING system SHUTDOWN"
 	echo "--------------------------------------------------------------"
@@ -62,15 +64,31 @@ smoke_tests()
 
 full_tests()
 {
-	# Currently this is a placeholder.
-	# This will be used to add the full tests scenario those are run in
-	# the CI system
 	echo
 	echo "--------------------------------------------------------------"
-	echo "BUILD sequence COMPLETED"
-	echo "IMAGE sequence COMPLETED"
 	echo "BOOT sequence COMPLETED"
 	echo "TEST sequence STARTED"
+	if [ "${istar}" -eq 1 ]; then
+		rm -fr ${metadir}
+		mkdir -p ${metadir}
+		tar xvf ${tardev} -C ${metadir}
+		cd /usr/tests
+		set +e
+		kyua test
+		rc=$?
+		set -e
+		if [ ${rc} -ne 0 ] && [ ${rc} -ne 1 ]; then
+			exit ${rc}
+		fi
+		kyua report --verbose --results-filter passed,skipped,xfail,broken,failed --output test-report.txt
+		kyua report-junit --output=test-report.xml
+		mv test-report.* /${metadir}
+		tar cvf ${tardev} -C ${metadir} .
+	else
+		echo "ERROR: no device with POSIX tar archive format found."
+		# Don't shutdown because this is not run in unattended mode
+		exit 1
+	fi
 	echo "TEST sequence COMPLETED"
 	echo "INITIATING system SHUTDOWN"
 	echo "--------------------------------------------------------------"
