MFC: 1.414, 1.415: Fixed the essential GID checks.
Prodded by:	gshapiro

diff --git a/Makefile.inc1 b/Makefile.inc1
--- a/Makefile.inc1
+++ b/Makefile.inc1
@@ -342,17 +342,25 @@ buildworld: ${WMAKE_TGTS}
 #
 # Checks to be sure system is ready for installworld
 #
-installcheck:
+CHECK_UIDS=
+CHECK_GIDS=
 .if !defined(NO_SENDMAIL)
-	@if ! `id -u smmsp > /dev/null`; then \
-		echo "ERROR: Required smmsp user is missing, see /usr/src/UPDATING."; \
-		false; \
-	fi
-	@if ! `id -g smmsp > /dev/null`; then \
-		echo "ERROR: Required smmsp group is missing, see /usr/src/UPDATING."; \
-		false; \
-	fi
+CHECK_UIDS+=	smmsp
+CHECK_GIDS+=	smmsp
 .endif
+installcheck:
+.for uid in ${CHECK_UIDS}
+	@if ! `id -u ${uid} >/dev/null 2>&1`; then \
+		echo "ERROR: Required ${uid} user is missing, see /usr/src/UPDATING."; \
+		false; \
+	fi
+.endfor
+.for gid in ${CHECK_GIDS}
+	@if ! `find / -prune -group ${gid} >/dev/null 2>&1`; then \
+		echo "ERROR: Required ${gid} group is missing, see /usr/src/UPDATING."; \
+		false; \
+	fi
+.endfor
 
 #
 # distributeworld
