Despite the fact that it is documented in the handbook, the release notes, and UPDATING and has been posted to both freebsd-current and freebsd-stable, users are still not adding the required smmsp user and group before doing an installworld.  Therefore, don't let users do an installworld unless they have followed directions.
Add a new installcheck Makefile target which installworld runs before
actually starting the installation.  This target can be used by other parts
of userland as well.  The first addition to the target is to check for the
smmsp user and group if NO_SENDMAIL isn't defined.

Others may add checks to this target as they see fit.

MFC after:	1 week


git-svn-id: svn+ssh://svn.freebsd.org/base/head@95146 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/Makefile.inc1 b/Makefile.inc1
--- a/Makefile.inc1
+++ b/Makefile.inc1
@@ -313,11 +313,28 @@ everything:
 	cd ${.CURDIR}; ${WMAKE} all
 
 #
+# installcheck
+#
+# Checks to be sure system is ready for installworld
+#
+installcheck:
+.if !defined(NO_SENDMAIL)
+	@if ! `grep -q '^smmsp:' /etc/passwd`; then \
+		echo "ERROR: Required smmsp user is missing, see /usr/src/UPDATING."; \
+		false; \
+	fi
+	@if ! `grep -q '^smmsp:' /etc/group`; then \
+		echo "ERROR: Required smmsp group is missing, see /usr/src/UPDATING."; \
+		false; \
+	fi
+.endif
+
+#
 # installworld
 #
 # Installs everything compiled by a 'buildworld'.
 #
-installworld:
+installworld: installcheck
 	mkdir -p ${INSTALLTMP}
 	for prog in [ awk cat chflags chmod chown date echo egrep find grep \
 	    ln make makewhatis mkdir mtree mv perl rm sed sh sysctl \
