Merge in all the changes that Mike Makonnen has been maintaining for a while. This is only the script pieces, the glue for the build comes next.
Submitted by:	Mike Makonnen <makonnen@pacbell.net>
Reviewed by:	silence on -current and -hackers
Prodded by:	rwatson

diff --git a/etc/rc.d/accounting b/etc/rc.d/accounting
--- a/etc/rc.d/accounting
+++ b/etc/rc.d/accounting
@@ -1,30 +1,54 @@
 #!/bin/sh
 #
-# $NetBSD: accounting,v 1.2 2000/05/13 08:45:06 lukem Exp $
+# $NetBSD: accounting,v 1.7 2002/03/22 04:33:57 thorpej Exp $
+# $FreeBSD$
 #
 
 # PROVIDE: accounting
 # REQUIRE: mountall
+# BEFORE: DAEMON
+# KEYWORD: FreeBSD NetBSD
 
 . /etc/rc.subr
 
 name="accounting"
-rcvar=$name
+rcvar=`set_rcvar`
+accounting_command="/usr/sbin/accton"
+accounting_file="/var/account/acct"
 start_cmd="accounting_start"
 stop_cmd="accounting_stop"
 
 accounting_start()
 {
-	if [ -f /var/account/acct ]; then
-		echo "Turning on accounting."
-		/usr/sbin/accton /var/account/acct
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		_dir=`dirname "$accounting_file"`
+		if [ ! -d `dirname "$_dir"` ]; then
+			if ! mkdir -p "$_dir" ; then
+				warn "Could not create $_dir."
+				return 1
+			fi
+		fi
+		if [ ! -e "$accounting_file" ]; then
+			touch "$accounting_file"
+		fi
+		;;
+	*)
+		;;
+	esac
+
+	if [ ! -f ${accounting_file} ]; then
+		echo "Creating accounting file ${accounting_file}"
+		( umask 022 ; > ${accounting_file} )
 	fi
+	echo "Turning on accounting."
+	${accounting_command} ${accounting_file}
 }
 
 accounting_stop()
 {
 	echo "Turning off accounting."
-	/usr/sbin/accton
+	${accounting_command}
 }
 
 load_rc_config $name
diff --git a/etc/rc.d/mountcritremote b/etc/rc.d/mountcritremote
--- a/etc/rc.d/mountcritremote
+++ b/etc/rc.d/mountcritremote
@@ -1,19 +1,89 @@
 #!/bin/sh
 #
-# $NetBSD: mountcritremote,v 1.2 2000/05/13 08:45:07 lukem Exp $
+# $NetBSD: mountcritremote,v 1.7 2002/04/29 12:29:53 lukem Exp $
+# $FreeBSD$
 #
 
 # PROVIDE: mountcritremote
-# REQUIRE: NETWORK root mountcritlocal
+# REQUIRE: NETWORKING root mountcritlocal
+# KEYWORD: FreeBSD NetBSD
 
 . /etc/rc.subr
 
-#	mount critical remote filesystems
-#	(as specified in $critical_filesystems)
-#
 name="mountcritremote"
-start_cmd="mount_critical_filesystems remote"
 stop_cmd=":"
+
+case `${CMD_OSTYPE}` in
+	FreeBSD)
+	start_cmd="mountcritremote_start"
+	start_precmd="mountcritremote_precmd"
+	;;
+NetBSD)
+	start_cmd="mountcritremote_start"
+	;;
+esac
+
+# Mount NFS filesystems if present in /etc/fstab
+#
+# XXX When the vfsload() issues with nfsclient support and related sysctls
+# have been resolved, this block can be removed, and the condition that
+# skips nfs in the following block (for "other network filesystems") can
+# be removed.
+#
+mountcritremote_precmd()
+{
+	case "`mount -d -a -t nfs 2> /dev/null`" in
+	*mount_nfs*)
+		# Handle absent nfs client support
+		if ! sysctl vfs.nfs >/dev/null 2>&1 ; then
+			kldload nfsclient || warn 'nfs mount ' \
+			    'requested, but no nfs client in kernel' \
+			return 1
+		fi
+		;;
+	esac
+	return 0
+}
+
+mountcritremote_start()
+{
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		# Mount nfs filesystems.
+		#
+		echo -n 'Mounting NFS file systems:'
+		mount -a -t nfs
+		echo '.'
+
+		# Mount other network filesystems if present in /etc/fstab
+		for i in ${networkfs_types}; do
+			fstype=${i%:*}
+			fsdecr=${i#*:}
+
+			[ "${fstype}" = "nfs" ] && continue
+
+			case "`mount -d -a -t ${fstype}`" in
+			*mount_${fstype}*)
+				echo -n "Mounting ${fsdecr} file systems:"
+				mount -a -t ${fstype}
+				echo '.'
+				;;
+			esac
+		done
+
+		# Cleanup /var again just in case it's a network mount 
+		/etc/rc.d/cleanvar start
+		rm -f /var/run/clean_var /var/spool/lock/clean_var
+		;;
+	NetBSD)
+		#	Mount critical filesystems that may be `remote'.
+		#	(as specified in $critical_filesystems_remote)
+		#	This usually includes /usr.
+		#
+		mount_critical_filesystems remote
+		;;
+	esac
+}
 
 load_rc_config $name
 run_rc_command "$1"
diff --git a/etc/rc.d/root b/etc/rc.d/root
--- a/etc/rc.d/root
+++ b/etc/rc.d/root
@@ -1,10 +1,12 @@
 #!/bin/sh
 #
-# $NetBSD: root,v 1.1.1.1 2000/03/10 11:53:24 lukem Exp $
+# $NetBSD: root,v 1.2 2000/05/13 08:45:09 lukem Exp $
+# $FreeBSD$
 #
 
 # PROVIDE: root
 # REQUIRE: fsck
+# KEYWORD: FreeBSD NetBSD
 
 . /etc/rc.subr
 
@@ -14,9 +16,35 @@ stop_cmd=":"
 
 root_start()
 {
-	umount -a >/dev/null 2>&1
-	mount /
-	rm -f /fastboot
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		# root normally must be read/write, but if this is a BOOTP NFS
+		# diskless boot it does not have to be.
+		#
+		case ${root_rw_mount} in
+		[Nn][Oo] | '')
+			;;
+		*)
+			if ! mount -u -o rw / ; then
+				echo 'Mounting root filesystem rw failed, startup aborted'
+				exit 1
+			fi
+			;;
+		esac
+
+		umount -a >/dev/null 2>&1
+		mount /
+
+		# If we booted a special kernel remove the record
+		# so we will boot the default kernel next time.
+		[ -e /boot/nextkernel ] && rm -f /boot/nextkernel
+		;;
+	NetBSD)
+		umount -a >/dev/null 2>&1
+		mount /
+		rm -f /fastboot
+		;;
+	esac
 }
 
 load_rc_config $name
