Load the g_md kernel module if needed.
Pointed out by:	Gianmarco Giovannelli
Submitted by:	matteo
MFC after:	3 days


git-svn-id: svn+ssh://svn.freebsd.org/base/head@154430 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/etc/rc.d/addswap b/etc/rc.d/addswap
--- a/etc/rc.d/addswap
+++ b/etc/rc.d/addswap
@@ -22,7 +22,15 @@ addswap_start()
 	[Nn][Oo] | '')
 		;;
 	*)
-		if [ -w "${swapfile}" -a -c /dev/mdctl ]; then
+		if [ -w "${swapfile}" ]; then
+			if ! kldstat -q -m g_md ; then
+				if kldload g_md ; then
+					info 'g_md module loaded.'
+				else
+					warn 'g_md module failed to load.'
+					return 1
+				fi
+			fi
 			echo "Adding ${swapfile} as additional swap"
 			mdev=`mdconfig -a -t vnode -f ${swapfile}` && swapon /dev/${mdev}
 		fi
