The sysctl(8) program exits on some errors and only emits warnings on others. In the case where it displayed warnings it would still return succesfully. Modify it so that it returns the number of sysctls that it was not able to set.
Make use of this in rc.d to display only *unsuccessfull* attempts to
set sysctls.

diff --git a/etc/rc.d/auto_linklocal b/etc/rc.d/auto_linklocal
--- a/etc/rc.d/auto_linklocal
+++ b/etc/rc.d/auto_linklocal
@@ -18,7 +18,10 @@ stop_cmd=":"
 auto_linklocal_start()
 {
 	if ! checkyesno ipv6_enable && ${SYSCTL} net.inet6 > /dev/null 2>&1; then
-		${SYSCTL_W} net.inet6.ip6.auto_linklocal=0
+		if ! ${SYSCTL_W} net.inet6.ip6.auto_linklocal=0 >/dev/null 2>&1; then
+			warn "failed to set sysctl(8)"
+			return 1
+		fi
 		laddr=`network6_getladdr lo0`
 		if [ -z "${laddr}" ]; then
 			ifconfig lo0 inet6 fe80::1 prefixlen 64
diff --git a/etc/rc.d/power_profile b/etc/rc.d/power_profile
--- a/etc/rc.d/power_profile
+++ b/etc/rc.d/power_profile
@@ -50,7 +50,11 @@ sysctl_set ()
 	esac
 
 	# Set the desired value
-	[ -n "${value}" ] && sysctl ${node}=${value}
+	if [ -n "${value}" ]; then
+		if ! sysctl ${node}=${value} > /dev/null 2>&1; then
+			warn "unable to set ${node}=${value}"
+		fi
+	fi
 }
 
 if [ $# -ne 1 ]; then
