Revise hcsecd(8) and sdpd(8) rc.d scripts one more time
- Use _prestart rc.d method to automatically kldload ng_btsocket(4) if needed;

- Rename "sdpd_user" to "sdpd_username" and "sdpd_group" to "sdpd_groupname"
  to avoid collision with "magic" variables;

Inspired by:	yar
MFC after:	3 days


git-svn-id: svn+ssh://svn.freebsd.org/base/head@152688 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/etc/rc.d/hcsecd b/etc/rc.d/hcsecd
--- a/etc/rc.d/hcsecd
+++ b/etc/rc.d/hcsecd
@@ -14,12 +14,20 @@ name="hcsecd"
 command="/usr/sbin/${name}"
 pidfile="/var/run/${name}.pid"
 rcvar=`set_rcvar`
-start_cmd="hcsecd_start"
+start_precmd="hcsecd_prestart"
 
-hcsecd_start()
+hcsecd_prestart()
 {
-	kldload ng_btsocket > /dev/null 2>&1
-	${command} ${command_args}
+	if ! kldstat -q -m ng_btsocket > /dev/null 2>&1 ; then
+		if kldload ng_btsocket > /dev/null 2>&1 ; then
+			info 'ng_btsocket module loaded'
+		else
+			warn 'ng_btsocket module failed to load'
+			return 1
+		fi
+	fi
+
+	return 0
 }
 
 load_rc_config $name
diff --git a/etc/rc.d/sdpd b/etc/rc.d/sdpd
--- a/etc/rc.d/sdpd
+++ b/etc/rc.d/sdpd
@@ -13,18 +13,26 @@
 name="sdpd"
 command="/usr/sbin/${name}"
 rcvar=`set_rcvar`
-start_cmd="sdpd_start"
+start_precmd="sdpd_prestart"
 
-sdpd_start()
+sdpd_prestart()
 {
-	kldload ng_btsocket > /dev/null 2>&1
-	${command} ${command_args}
+	if ! kldstat -q -m ng_btsocket > /dev/null 2>&1 ; then
+		if kldload ng_btsocket > /dev/null 2>&1 ; then
+			info 'ng_btsocket module loaded'
+		else
+			warn 'ng_btsocket module failed to load'
+			return 1
+		fi
+	fi
+
+	return 0
 }
 
 load_rc_config $name
 control="${sdpd_control:-/var/run/sdp}"
-group="${sdpd_group:-nobody}"
-user="${sdpd_user:-nobody}"
+group="${sdpd_groupname:-nobody}"
+user="${sdpd_username:-nobody}"
 command_args="-c ${control} -g ${group} -u ${user}"
 
 run_rc_command "$1"
