Merge in all the changes that Mike Makonnen has been maintaining for a while. This is only the script pieces, the glue for the build comes next.
Submitted by:	Mike Makonnen <makonnen@pacbell.net>
Reviewed by:	silence on -current and -hackers
Prodded by:	rwatson

diff --git a/etc/rc.d/ipfilter b/etc/rc.d/ipfilter
--- a/etc/rc.d/ipfilter
+++ b/etc/rc.d/ipfilter
@@ -1,27 +1,60 @@
 #!/bin/sh
 #
-# $NetBSD: ipfilter,v 1.8 2000/10/01 05:58:06 lukem Exp $
+# $NetBSD: ipfilter,v 1.10 2001/02/28 17:03:50 lukem Exp $
+# $FreeBSD$
 #
 
 # PROVIDE: ipfilter
 # REQUIRE: root beforenetlkm mountcritlocal tty
+# KEYWORD: FreeBSD NetBSD
 
 . /etc/rc.subr
 
 name="ipfilter"
-rcvar=$name
+rcvar=`set_rcvar`
+load_rc_config $name
+
+case `${CMD_OSTYPE}` in
+FreeBSD)
+	stop_precmd="test -f ${ipfilter_rules}"
+	;;
+NetBSD)
+	stop_precmd="test -f /etc/ipf.conf -o -f /etc/ipf6.conf"
+	;;
+esac
+
 start_precmd="ipfilter_prestart"
 start_cmd="ipfilter_start"
-stop_precmd="test -f /etc/ipf.conf -o -f /etc/ipf6.conf"
 stop_cmd="ipfilter_stop"
 reload_precmd="$stop_precmd"
 reload_cmd="ipfilter_reload"
+resync_precmd="$stop_precmd"
+resync_cmd="ipfilter_resync"
 status_precmd="$stop_precmd"
 status_cmd="ipfilter_status"
-extra_commands="reload status"
+extra_commands="reload resync status"
 
 ipfilter_prestart()
 {
+case `${CMD_OSTYPE}` in
+FreeBSD)
+	# load ipfilter kernel module if needed
+	if ! sysctl net.inet.ipf.fr_pass > /dev/null 2>&1; then
+		if kldload ipl ; then
+			echo 'IP-filter module loaded.'
+		else
+			warn 'IP-filter module failed to load.'
+			return 1
+		fi
+	fi
+
+	# check for ipfilter rules
+	if [ ! -r "${ipfilter_rules}" ]; then
+		warn 'IP-filter: NO IPF RULES'
+		return 1
+	fi
+	;;
+NetBSD)
 	if [ ! -f /etc/ipf.conf ] && [ ! -f /etc/ipf6.conf ]; then
 		warn "/etc/ipf*.conf not readable; ipfilter start aborted."
 			#
@@ -35,23 +68,42 @@ ipfilter_prestart()
 		fi
 		return 1
 	fi
+	;;
+esac
 	return 0
 }
 
 ipfilter_start()
 {
 	echo "Enabling ipfilter."
-	/sbin/ipf -E -Fa
-	if [ -f /etc/ipf.conf ]; then
-		/sbin/ipf -f /etc/ipf.conf
-	fi
-	if [ -f /etc/ipf6.conf ]; then
-		/sbin/ipf -6 -f /etc/ipf6.conf
-	fi
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		${ipfilter_program:-/sbin/ipf} -Fa -f \
+	    	    "${ipfilter_rules}" ${ipfilter_flags}
+		;;
+	NetBSD)
+		/sbin/ipf -E -Fa
+		if [ -f /etc/ipf.conf ]; then
+			/sbin/ipf -f /etc/ipf.conf
+		fi
+		if [ -f /etc/ipf6.conf ]; then
+			/sbin/ipf -6 -f /etc/ipf6.conf
+		fi
+		;;
+	esac
 }
 
 ipfilter_stop()
 {
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		echo "Saving firewall state tables"
+		${ipfs_program:-/sbin/ipfs} -W ${ipfs_flags}
+		;;
+	NetBSD)
+		;;
+	esac
+	# XXX - The following command is not effective for 'lkm's
 	echo "Disabling ipfilter."
 	/sbin/ipf -D
 }
@@ -60,20 +112,42 @@ ipfilter_reload()
 {
 	echo "Reloading ipfilter rules."
 
-	/sbin/ipf -I -Fa
-	if [ -f /etc/ipf.conf ] && ! /sbin/ipf -I -f /etc/ipf.conf; then
-		err 1 "reload of ipf.conf failed; not swapping to new ruleset."
-	fi
-	if [ -f /etc/ipf6.conf ] && ! /sbin/ipf -I -6 -f /etc/ipf6.conf; then
-		err 1 "reload of ipf6.conf failed; not swapping to new ruleset."
-	fi
-	/sbin/ipf -s
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		${ipfilter_program:-/sbin/ipf} -I -Fa -f \
+	    	    "${ipfilter_rules}" ${ipfilter_flags}
+		;;
+	NetBSD)
+		/sbin/ipf -I -Fa
+		if [ -f /etc/ipf.conf ] && ! /sbin/ipf -I -f /etc/ipf.conf; then
+			err 1 "reload of ipf.conf failed; not swapping to" \
+			    " new ruleset."
+		fi
+		if [ -f /etc/ipf6.conf ] && \
+		    ! /sbin/ipf -I -6 -f /etc/ipf6.conf; then
+			err 1 "reload of ipf6.conf failed; not swapping to" \
+			    " new ruleset."
+		fi
+		/sbin/ipf -s
+		;;
+	esac
+
+}
+
+ipfilter_resync()
+{
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		# Don't resync if ipfilter is not loaded
+		[ sysctl net.inet.ipf.fr_pass > /dev/null 2>&1 ] && return
+		;;
+	esac
+	${ipfilter_program:-/sbin/ipf} -y ${ipfilter_flags}
 }
 
 ipfilter_status()
 {
-	/sbin/ipf -V
+	${ipfilter_program:-/sbin/ipf} -V
 }
 
-load_rc_config $name
 run_rc_command "$1"
diff --git a/etc/rc.d/securelevel b/etc/rc.d/securelevel
--- a/etc/rc.d/securelevel
+++ b/etc/rc.d/securelevel
@@ -1,10 +1,13 @@
 #!/bin/sh
 #
-# $NetBSD: securelevel,v 1.1 2000/08/21 23:31:24 lukem Exp $
+# $NetBSD: securelevel,v 1.4 2002/03/22 04:34:00 thorpej Exp $
+# $FreeBSD$
 #
 
 # PROVIDE: securelevel
 # REQUIRE: aftermountlkm ipnat mountd
+# BEFORE:  DAEMON
+# KEYWORD: FreeBSD NetBSD
 
 . /etc/rc.subr
 
@@ -14,19 +17,39 @@ stop_cmd=":"
 
 securelevel_start()
 {
-	#	if $securelevel is set, change it here, else if it is 0,
-	#	change it to 1 here, before we start daemons or login services.
-	#
-	if [ -n "$securelevel" ]; then
-		echo -n "Setting securelevel: "
-		sysctl kern.securelevel=$securelevel
-	else
-		securelevel=`sysctl -n kern.securelevel`
-		if [ x"$securelevel" = x0 ]; then
-			echo -n "Setting securelevel: "
-			sysctl kern.securelevel=1
+	case `${CMD_OSTYPE}` in
+	FreeBSD)
+		case ${kern_securelevel_enable} in
+		[Yy][Ee][Ss])
+			if [ ${kern_securelevel} -ge 0 ]; then
+				echo 'Raising kernel security level: '
+				${SYSCTL_W} kern.securelevel=${kern_securelevel}
+			fi
+			;;
+		esac
+		;;
+	NetBSD)
+		#	if $securelevel is set higher, change it here, else if
+		#	it is 0, change it to 1 here, before we start daemons
+		#	or login services.
+		#
+		osecurelevel=`sysctl -n kern.securelevel`
+		if [ -n "$securelevel" -a "$securelevel" != "$osecurelevel" ]; then
+			if [ "$securelevel" -lt "$osecurelevel" ]; then
+				echo "Can't lower securelevel."
+				exit 1
+			else
+				echo -n "Setting securelevel: "
+				${SYSCTL_W} kern.securelevel=$securelevel
+			fi
+		else
+			if [ "$osecurelevel" = 0 ]; then
+				echo -n "Setting securelevel: "
+				${SYSCTL_W} kern.securelevel=1
+			fi
 		fi
- 	fi
+		;;
+	esac
 }
 
 load_rc_config $name
