Ensure that the load of rules into the alternate ruleset worked before loading them into the live one too.
PR:		conf/97311
Submitted by:	David Bushong
Reviewed by:	silence on rc@
Approved by:	ru (mentor)
MFC after:	10 days


git-svn-id: svn+ssh://svn.freebsd.org/base/head@164175 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/etc/rc.d/ipfilter b/etc/rc.d/ipfilter
--- a/etc/rc.d/ipfilter
+++ b/etc/rc.d/ipfilter
@@ -93,11 +93,17 @@ ipfilter_reload()
 	if [ -r "${ipfilter_rules}" ]; then
 		${ipfilter_program:-/sbin/ipf} -I \
 		    -f "${ipfilter_rules}" ${ipfilter_flags}
+		if [ $? -ne 0 ]; then
+			err 1 'Load of rules into alternate set failed; aborting reload'
+		fi
 	fi
 	${ipfilter_program:-/sbin/ipf} -I -6 -Fa
 	if [ -r "${ipv6_ipfilter_rules}" ]; then
 		${ipfilter_program:-/sbin/ipf} -I -6 \
 		    -f "${ipv6_ipfilter_rules}" ${ipfilter_flags}
+		if [ $? -ne 0 ]; then
+			err 1 'Load of IPv6 rules into alternate set failed; aborting reload'
+		fi
 	fi
 	${ipfilter_program:-/sbin/ipf} -s
 
