No need to display the result of enabling the ipfw sysctl if it's successfull. Issue a warning if it fails, however.

diff --git a/etc/rc.d/ipfw b/etc/rc.d/ipfw
--- a/etc/rc.d/ipfw
+++ b/etc/rc.d/ipfw
@@ -51,7 +51,9 @@ ipfw_start()
 
 	# Enable the firewall
 	#
-	${SYSCTL_W} net.inet.ip.fw.enable=1
+	if ! ${SYSCTL_W} net.inet.ip.fw.enable=1 1>/dev/null 2>&1; then
+		warn "failed to enable firewall"
+	fi
 }
 
 ipfw_stop()
