style(9)

diff --git a/etc/rc.d/jail b/etc/rc.d/jail
--- a/etc/rc.d/jail
+++ b/etc/rc.d/jail
@@ -221,19 +221,19 @@ jail_start()
 		_tmp_jail=${_tmp_dir}/jail.$$
 		eval jail ${_flags} -i ${_rootdir} ${_hostname} \
 			${_ip} ${_exec_start} > ${_tmp_jail} 2>&1
-			if [ "$?" -eq 0 ] ; then
-				echo -n " $_hostname"
-				_jail_id=$(head -1 ${_tmp_jail})
-				tail +2 ${_tmp_jail} >${_rootdir}/var/log/console.log
-				echo ${_jail_id} > /var/run/jail_${_jail}.id
-			else
-				jail_umount_fs
-				if [ -n "${jail_interface}" ]; then
-					ifconfig ${jail_interface} -alias ${jail_ip}
-				fi
-				echo " cannot start jail \"${_jail}\": "
-				tail +2 ${_tmp_jail}
+		if [ "$?" -eq 0 ] ; then
+			echo -n " $_hostname"
+			_jail_id=$(head -1 ${_tmp_jail})
+			tail +2 ${_tmp_jail} >${_rootdir}/var/log/console.log
+			echo ${_jail_id} > /var/run/jail_${_jail}.id
+		else
+			jail_umount_fs
+			if [ -n "${jail_interface}" ]; then
+				ifconfig ${jail_interface} -alias ${jail_ip}
 			fi
+			echo " cannot start jail \"${_jail}\": "
+			tail +2 ${_tmp_jail}
+		fi
 		rm -f ${_tmp_jail}
 	done
 	rmdir ${_tmp_dir}
