Quiet down rc.d/nfsclient by not printing anything in 'quiet' mode. Instead issue a warning of it fails to set the sysctls.
git-svn-id: svn+ssh://svn.freebsd.org/base/head@180294 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/etc/rc.d/nfsclient b/etc/rc.d/nfsclient
--- a/etc/rc.d/nfsclient
+++ b/etc/rc.d/nfsclient
@@ -22,11 +22,15 @@ nfsclient_start()
 	#
 
 	if [ -n "${nfs_access_cache}" ]; then
-		echo "NFS access cache time=${nfs_access_cache}"
-		sysctl vfs.nfs.access_cache_timeout=${nfs_access_cache} >/dev/null
+		[ -z "${rc_quiet}" ] && echo "NFS access cache time=${nfs_access_cache}"
+		if ! sysctl vfs.nfs.access_cache_timeout=${nfs_access_cache} >/dev/null; then
+			warn "failed to set access cache timeout"
+		fi
 	fi
 	if [ -n "${nfs_bufpackets}" ]; then
-		 sysctl vfs.nfs.bufpackets=${nfs_bufpackets} > /dev/null
+		if ! sysctl vfs.nfs.bufpackets=${nfs_bufpackets} > /dev/null; then
+			warn "failed to set vfs.nfs.bufpackets"
+		fi
 	fi
 
 	unmount_all
