MFC: r291536 Add support for the new "-manage-gids" option for the nfsuserd daemon to the rc scripts. With these changes, setting nfs_server_managegids="YES" in /etc/rc.conf will enable this capability.
Relnotes:	yes

diff --git a/etc/rc.d/nfsd b/etc/rc.d/nfsd
--- a/etc/rc.d/nfsd
+++ b/etc/rc.d/nfsd
@@ -46,9 +46,13 @@ nfsd_precmd()
 			sysctl vfs.nfsd.nfs_privport=0 > /dev/null
 		fi
 
+		if checkyesno nfsv4_server_enable || \
+		    checkyesno nfs_server_managegids; then
+			force_depend nfsuserd || err 1 "Cannot run nfsuserd"
+		fi
+
 		if checkyesno nfsv4_server_enable; then
 			sysctl vfs.nfsd.server_max_nfsvers=4 > /dev/null
-			force_depend nfsuserd || err 1 "Cannot run nfsuserd"
 		else
 			echo 'NFSv4 is disabled'
 			sysctl vfs.nfsd.server_max_nfsvers=3 > /dev/null
