Luke Mewburn has indicated that they (NetBSD) are not interested in keeping the scripts under rc.d in sync with us. So, remove NetBSD specific stuff (which made our scripts more complicated than necessary).
The NetBSD ident string will be left intact, both for history and
also incase we wish to pull in future versions.

diff --git a/etc/rc.d/root b/etc/rc.d/root
--- a/etc/rc.d/root
+++ b/etc/rc.d/root
@@ -16,36 +16,27 @@ stop_cmd=":"
 
 root_start()
 {
-	case ${OSTYPE} in
-	FreeBSD)
-		# root normally must be read/write, but if this is a BOOTP NFS
-		# diskless boot it does not have to be.
-		#
-		case ${root_rw_mount} in
-		[Nn][Oo] | '')
-			;;
-		*)
-			if ! mount -u -o rw /; then
-				echo 'Mounting root filesystem rw failed, startup aborted'
-				/bin/kill -QUIT $$
-			fi
-			;;
-		esac
-
-		umount -a >/dev/null 2>&1
-
-		# If we booted a special kernel remove the record
-		# so we will boot the default kernel next time.
-		if [ -e /boot/nextkernel ]; then
-			rm -f /boot/nextkernel
+	# root normally must be read/write, but if this is a BOOTP NFS
+	# diskless boot it does not have to be.
+	#
+	case ${root_rw_mount} in
+	[Nn][Oo] | '')
+		;;
+	*)
+		if ! mount -u -o rw /; then
+			echo 'Mounting root filesystem rw failed, startup aborted'
+			/bin/kill -QUIT $$
 		fi
 		;;
-	NetBSD)
-		umount -a >/dev/null 2>&1
-		mount /
-		rm -f /fastboot
-		;;
 	esac
+
+	umount -a >/dev/null 2>&1
+
+	# If we booted a special kernel remove the record
+	# so we will boot the default kernel next time.
+	if [ -e /boot/nextkernel ]; then
+		rm -f /boot/nextkernel
+	fi
 }
 
 load_rc_config $name
