Sync with NetBSD's mainline.

diff --git a/etc/rc.d/securelevel b/etc/rc.d/securelevel
--- a/etc/rc.d/securelevel
+++ b/etc/rc.d/securelevel
@@ -1,10 +1,11 @@
 #!/bin/sh
 #
-# $NetBSD: securelevel,v 1.1 2000/08/21 23:31:24 lukem Exp $
+# $NetBSD: securelevel,v 1.3 2002/03/01 17:58:00 mrg Exp $
 #
 
 # PROVIDE: securelevel
 # REQUIRE: aftermountlkm ipnat mountd
+# BEFORE:  DAEMON
 
 . /etc/rc.subr
 
@@ -14,15 +15,21 @@ stop_cmd=":"
 
 securelevel_start()
 {
-	#	if $securelevel is set, change it here, else if it is 0,
-	#	change it to 1 here, before we start daemons or login services.
+	#	if $securelevel is set higher, change it here, else if
+	#	it is 0, change it to 1 here, before we start daemons
+	#	or login services.
 	#
-	if [ -n "$securelevel" ]; then
-		echo -n "Setting securelevel: "
-		sysctl -w kern.securelevel=$securelevel
+	osecurelevel=`sysctl -n kern.securelevel`
+	if [ -n "$securelevel" -a "$securelevel" != "$osecurelevel" ]; then
+		if [ "$securelevel" -lt "$osecurelevel" ]; then
+			echo "Can't lower securelevel."
+			exit 1
+		else
+			echo -n "Setting securelevel: "
+			sysctl -w kern.securelevel=$securelevel
+		fi
 	else
-		securelevel=`sysctl -n kern.securelevel`
-		if [ x"$securelevel" = x0 ]; then
+		if [ "$osecurelevel" = 0 ]; then
 			echo -n "Setting securelevel: "
 			sysctl -w kern.securelevel=1
 		fi
