MFC: 	Set MAKEDEVPATH in sysinstall to include the necessary /mnt2 stuff 	before starting the fixit shell so that MAKEDEV on the fixit floppy 	(which would otherwise hardcode its path to /sbin:/bin) is usable.
	Search for mknod in the path instead of hardcoding /sbin/mknod
	in MAKEDEV.

PR:		misc/21241
Approved by:	jkh

diff --git a/etc/MAKEDEV b/etc/MAKEDEV
--- a/etc/MAKEDEV
+++ b/etc/MAKEDEV
@@ -187,11 +187,18 @@ dkminor()
 }
 
 # Override mknod(2) to add extra handling to it.
+mknod=/sbin/mknod
+for i in `IFS=':'; echo $PATH`; do
+	if [ -x "${i}/mknod" ]; then
+		mknod="${i}/mknod"
+		break
+	fi
+done
 mknod() {
 	rm -f "$1" || exit 1
 	case $# in
-	4) /sbin/mknod "$@" root:wheel || die 2 "/sbin/mknod $@ failed";;
-	5) /sbin/mknod "$@"            || die 2 "/sbin/mknod $@ failed";;
+	4) "$mknod" "$@" root:wheel || die 2 "$mknod $@ failed";;
+	5) "$mknod" "$@"            || die 2 "$mknod $@ failed";;
 	*) die 2 "bad node: mknod $@";;
 	esac
 }
