Catch up with changes made in -CURRENT branch.
Egged-on-by:  jkh

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,5 +1,5 @@
 #!/bin/sh
-#	$Id: rc,v 1.168 1999/01/18 03:25:10 grog Exp $
+#	$Id: rc,v 1.175 1999/01/31 04:28:51 grog Exp $
 #	From: @(#)rc	5.27 (Berkeley) 6/5/91
 
 # System startup script run by init on autoboot
@@ -22,23 +22,38 @@ HOME=/; export HOME
 PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin
 export PATH
 
-# Configure ccd devices.
-if [ -f /etc/ccd.conf ]; then
-	ccdconfig -C
-fi
-
-if [ -n "$vinum_slices" ]; then
-	if [ -r /modules/vinum.ko ]; then	# jkh paranoia
-		kldload vinum
-		vinum read $vinum_slices
-	else
-		echo "Can't find /modules/vinum.ko"
+# BOOTP diskless boot.  We have to run the rc file early in order to
+# handle read-only NFS mounts, where the various config files
+# in /etc often don't apply.   rc.diskless typically sets skip_diskconf=YES
+# on return.
+#
+if [ -f /etc/rc.diskless ]; then
+	dlv=`/sbin/sysctl -n vfs.nfs.diskless_valid 2> /dev/null`
+	if [ ${dlv:=0} != 0 ]; then
+		. /etc/rc.diskless
 	fi
 fi
 
-swapon -a
+# If there is a global system configuration file, suck it in.
+#
+if [ -f /etc/rc.conf ]; then
+	. /etc/rc.conf
+fi
 
-if [ $1x = autobootx ]; then
+# Configure ccd devices.
+if [ "X$skip_diskconf" != "XYES" -a -f /etc/ccd.conf ]; then
+	ccdconfig -C
+fi
+
+if [ "X$skip_diskconf" != "XYES" -a -n "$vinum_drives" ]; then
+	vinum read $vinum_drives
+fi
+
+if [ "X$skip_diskconf" != "XYES" ]; then
+	swapon -a
+fi
+
+if [ "X$skip_diskconf" != "XYES" -a $1x = autobootx ]; then
 	echo Automatic reboot in progress...
 	fsck -p
 	case $? in
@@ -75,25 +90,34 @@ fi
 
 trap "echo 'Reboot interrupted'; exit 1" 3
 
-# root must be read/write for NFS diskless before proceeding any further.
-mount -u -o rw /
-if [ $? != 0 ]; then
-	echo "Filesystem mount failed, startup aborted"
-	exit 1
+# root normally must be read/write, but if this is a BOOTP NFS
+# diskless boot it does not have to be.
+#
+
+if [ "X$skip_diskconf" != "XYES" ]; then
+	mount -u -o rw /
+
+	if [ $? != 0 ]; then
+		echo "Filesystem mount failed, startup aborted"
+		exit 1
+	fi
+
+	umount -a >/dev/null 2>&1
+
+	mount -a -t nonfs
+	if [ $? != 0 ]; then
+		echo "Filesystem mount failed, startup aborted"
+		exit 1
+	fi
 fi
 
-umount -a >/dev/null 2>&1
+# Run custom disk mounting function here
+#
 
-mount -a -t nonfs
-if [ $? != 0 ]; then
-	echo "Filesystem mount failed, startup aborted"
-	exit 1
+if [ "X$diskless_mount_func" != "X" ]; then
+        $diskless_mount_func
 fi
 
-# If there is a global system configuration file, suck it in.
-if [ -f /etc/rc.conf ]; then
-	. /etc/rc.conf
-fi
 
 # If old file exists, whine until they fix it.
 if [ -f /etc/sysconfig ]; then
@@ -389,10 +413,13 @@ fi
 # ---- rc.local  ----
 #
 
-if [ -f /etc/rc.local ]; then
-    echo -n 'starting local daemons:'
-    sh /etc/rc.local
-    echo '.'
+# Do traditional rc.local file if it exists. 
+# 
+
+if [ -f $conf_dir/rc.local ]; then
+	echo -n 'starting local daemons:'
+        sh $conf_dir/rc.local
+	echo '.'
 fi
 
 # Raise kernel security level.  This should be done only after `fsck' has
