If the initial attempt to write ${entropy_file} to /dev/random fails and the randomdev.ko module is not resident, try to load the module and perform the write again.
Reviewed by:	markm


git-svn-id: svn+ssh://svn.freebsd.org/base/head@63793 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -138,9 +138,17 @@ case ${entropy_file} in
 [Nn][Oo] | '')
 	;;
 *)
-	if [ -f ${entropy_file} -a -r ${entropy_file} ]; then
+	if [ -f ${entropy_file} -a -r ${entropy_file} -a -w /dev/random ]; then
 		echo "Reading entropy file"
-		cat ${entropy_file} > /dev/random
+		if ! cat ${entropy_file} 2>/dev/null >/dev/random; then
+			if ! kldstat -n randomdev >/dev/null 2>&1; then
+				kldload randomdev && \
+				    cat ${entropy_file} 2>/dev/null >/dev/random
+			fi
+		fi
+		if [ $? != 0 ]; then
+			echo "Writing entropy file to /dev/random failed"
+		fi
 		rm -f ${entropy_file}
 	fi
 	;;
