MFC: Heimdal 0.3e (MIT mucho-compatible) upgrade.

diff --git a/crypto/heimdal/lib/auth/sia/Makefile.am b/crypto/heimdal/lib/auth/sia/Makefile.am
--- a/crypto/heimdal/lib/auth/sia/Makefile.am
+++ b/crypto/heimdal/lib/auth/sia/Makefile.am
@@ -1,4 +1,4 @@
-# $Id: Makefile.am,v 1.5 1999/12/30 03:47:03 assar Exp $
+# $Id: Makefile.am,v 1.8 2001/01/29 22:38:36 assar Exp $
 
 include $(top_srcdir)/Makefile.am.common
 
@@ -17,6 +17,7 @@ KAFS=$(top_builddir)/lib/kafs/.libs/libkafs.a
 KAFS_S=$(top_builddir)/lib/kafs/.libs/libkafs.so
 endif
 
+if KRB5
 L = \
 	$(KAFS)						\
 	$(top_builddir)/lib/krb5/.libs/libkrb5.a	\
@@ -39,26 +40,69 @@ L_shared = \
 	$(LIB_getpwnam_r)				\
 	-lc
 
-EXTRA_DIST = sia.c krb5_matrix.conf krb5+c2_matrix.conf security.patch
+MOD = libsia_krb5.so
+
+else
+
+L = \
+	$(KAFS)						\
+	$(top_builddir)/lib/kadm/.libs/libkadm.a	\
+	$(top_builddir)/lib/krb/.libs/libkrb.a		\
+	$(top_builddir)/lib/des/.libs/libdes.a		\
+	$(top_builddir)/lib/com_err/.libs/libcom_err.a	\
+	$(top_builddir)/lib/roken/.libs/libroken.a	\
+	$(LIB_getpwnam_r)				\
+	-lc
+
+L_shared = \
+	$(KAFS_S)					\
+	$(top_builddir)/lib/kadm/.libs/libkadm.so	\
+	$(top_builddir)/lib/krb/.libs/libkrb.so		\
+	$(top_builddir)/lib/des/.libs/libdes.so		\
+	$(top_builddir)/lib/com_err/.libs/libcom_err.so	\
+	$(top_builddir)/lib/roken/.libs/libroken.so	\
+	$(LIB_getpwnam_r)				\
+	-lc
+
+MOD = libsia_krb4.so
+
+endif
+
+EXTRA_DIST = sia.c krb4_matrix.conf krb4+c2_matrix.conf \
+	krb5_matrix.conf krb5+c2_matrix.conf security.patch
 
 foodir = $(libdir)
-foo_DATA = libsia_krb5.so
+foo_DATA = $(MOD)
 
 LDFLAGS = -rpath $(libdir) -hidden -exported_symbol siad_\* 
 
 OBJS = sia.o posix_getpw.o
 
 libsia_krb5.so: $(OBJS)
-	if test -f $(top_builddir)/lib/krb5/.libs/libkrb5.a; then \
+	@if test -f $(top_builddir)/lib/krb5/.libs/libkrb5.a; then \
+		echo "ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L)"; \
 		ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L); \
 	elif test -f $(top_builddir)/lib/krb5/.libs/libkrb5.so; then \
+		echo "ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L_shared)"; \
 		ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L_shared); \
 	else \
 		echo "missing libraries"; exit 1; \
 	fi
 	ostrip -x -z $@
 
-CLEANFILES = libsia_krb5.so $(OBJS) so_locations
+libsia_krb4.so: $(OBJS)
+	@if test -f $(top_builddir)/lib/krb/.libs/libkrb.a; then \
+		echo "ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L)"; \
+		ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L); \
+	elif test -f $(top_builddir)/lib/krb/.libs/libkrb.so; then \
+		echo "ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L_shared)"; \
+		ld -shared -o $@ $(LDFLAGS) $(OBJS) $(L_shared); \
+	else \
+		echo "missing libraries"; exit 1; \
+	fi
+	ostrip -x $@
+
+CLEANFILES = $(MOD) $(OBJS) so_locations
 
 SUFFIXES += .c .o
 
