Add -s labels to vnconfig. Remove some unused error messages.
Reported-By: Bruce Montague and others
Approved-By: jkh

diff --git a/release/picobsd/build/picobsd b/release/picobsd/build/picobsd
--- a/release/picobsd/build/picobsd
+++ b/release/picobsd/build/picobsd
@@ -566,26 +566,14 @@ fail() {
     mtree)
 	echo "Error while making hierarchy in ${MFS_MOUNTPOINT}"
 	;;
-    makedevs)
-	echo "Error while making devices in ${MFS_MOUNTPOINT}"
-	;;
     crunch)
 	echo "Error while building ${name}."
-	;;
-    vnconfig2)
-	echo "Error while doing vnconfig of floppy.img on /dev/rvn${VNUM}..."
 	;;
     floppy_disklabel)
 	echo "Error while doing disklabel on of floppy.img size $FLOPPY_SIZE"
 	;;
-    kernel_compress)
-	echo "Error while copying compressed kernel to disk"
-	;;
-    mfs_compress)
-	echo "Error while copying compressed mfs image to disk"
-	;;
     missing_kernel)
-	echo "-> ERROR: you must build PICOBSD${suffix} kernel first"
+	echo "Error: you must build PICOBSD${suffix} kernel first"
 	;;
     "")
 	echo "User break"
@@ -610,7 +598,7 @@ init_fs_image() { # filename size_in_kbytes
     dd if=/dev/zero of=${imgname} count=${imgsize} bs=1k 2> /dev/null
     dd if=${boot1}  of=${imgname} conv=notrunc 2> /dev/null
 
-    vnconfig -c vn${VNUM} ${imgname} || fail $? no_vnconfig
+    vnconfig -c -s labels vn${VNUM} ${imgname} || fail $? no_vnconfig
 }
 
 
