Cleanup the build scripts.
Approved-by: jordan


git-svn-id: svn+ssh://svn.freebsd.org/base/head@57038 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/release/picobsd/build/stage1 b/release/picobsd/build/stage1
--- a/release/picobsd/build/stage1
+++ b/release/picobsd/build/stage1
@@ -9,6 +9,7 @@
 set -e	# abort in case of untested errors
 
 MFS_NAME=fs.PICOBSD
+MFS_MOUNTPOINT=/mnt
 # fail errno errcode
 # This function is used to trap errors and print msgs
 #
@@ -22,16 +23,16 @@ fail() {
 	echo "   Most probably your running kernel doesn't have the vn(4) device."
 	;;
     disklabel)
-	echo "Error while labeling ${MFS_NAME} size $SIZE"
+	echo "Error while labeling ${MFS_NAME} size ${MFS_SIZE}"
 	;;
     no_mount)
-	echo "Error while mounting ${MFS_NAME} (/dev/vn0c) on /mnt"
+	echo "Error while mounting ${MFS_NAME} (/dev/vn0c) on ${MFS_MOUNTPOINT}"
 	;;
     mtree)
-	echo "Error while making hierarchy in /mnt"
+	echo "Error while making hierarchy in ${MFS_MOUNTPOINT}"
 	;;
     makedevs)
-	echo "Error while making devices in /mnt"
+	echo "Error while making devices in ${MFS_MOUNTPOINT}"
 	;;
     crunch)
 	echo "Error while building ../${TYPE}/crunch1..."
@@ -56,191 +57,217 @@ fail() {
     exit 10
 }
 
-echo "-> Preparing MFS filesystem..."
-umount /dev/vn0 2> /dev/null || true
-umount /mnt 2> /dev/null || true
-vnconfig -u /dev/rvn0 2> /dev/null || true
+rm -f kernel.gz ${MFS_NAME}    # cleanup...
 
-dd of=${MFS_NAME} if=/dev/zero count=${SIZE} bs=1k 2> /dev/null
+create_mfs() {
+    echo "-> Preparing MFS filesystem..."
+    umount /dev/vn0 2> /dev/null || true
+    umount ${MFS_MOUNTPOINT} 2> /dev/null || true
+    vnconfig -u /dev/rvn0 2> /dev/null || true
 
-awk 'BEGIN {printf "%c%c", 85, 170}' | \
-    dd of=${MFS_NAME} obs=1 seek=510 conv=notrunc  2> /dev/null
+    dd of=${MFS_NAME} if=/dev/zero count=${MFS_SIZE} bs=1k 2> /dev/null
 
-vnconfig -s labels -c /dev/rvn0 ${MFS_NAME} 2>/dev/null || fail $? no_vnconfig
+    awk 'BEGIN {printf "%c%c", 85, 170}' | \
+	dd of=${MFS_NAME} obs=1 seek=510 conv=notrunc  2> /dev/null
 
-dd if=/boot/boot1 of=${MFS_NAME} conv=notrunc 2> /dev/null
+    vnconfig -s labels -c /dev/rvn0 ${MFS_NAME} 2>/dev/null || \
+	    fail $? no_vnconfig
 
-# This command does weird things on 2.2.x systems.
-# For small image sizes, use std disktypes
-if [ ${SIZE} -lt 1024 ] ; then
-	disklabel -rw /dev/rvn0 fd${SIZE} || fail $? disklabel
-else
-	disklabel -rw vn0 auto || fail $? disklabel
-fi
+    dd if=/boot/boot1 of=${MFS_NAME} conv=notrunc 2> /dev/null
 
-newfs -i ${MFS_INODES} -m 0 -p 0 -o space /dev/rvn0c
-mount /dev/vn0c /mnt || fail $? no_mount
-
-pwd=`pwd`
-
-echo "-> Populating MFS tree..."
-cd ../${TYPE}
-make -f Makefile.mfs || fail $? mtree
-if [ X"${NO_DEVFS}" != X"" ] ; then
-    make -f Makefile.mfs devnodes || fail $? makedevs
-fi
-
-MFS_RC=floppy.tree/etc/mfs.rc
-if [ ! -f ${MFS_RC} ] ; then # no private version. use generic mfs.rc
-    MFS_RC=${BUILDDIR}/../${MFS_RC}
-fi
-if [ "${INIT}" = "oinit" ] ; then
-    cat ${MFS_RC} | sed -e "s/@VER@/${VER}/g" > /mnt/etc/oinit.rc
-else
-    cat ${MFS_RC} | sed -e "s/@VER@/${VER}/g" > /mnt/etc/rc
-    if [ -f floppy.tree/etc/mfs.login.conf ] ; then
-	cp floppy.tree/etc/mfs.login.conf /mnt/etc/login.conf
+    # This command does weird things on 2.2.x systems.
+    # For small image sizes, use std disktypes
+    if [ ${MFS_SIZE} -lt 1024 ] ; then
+	disklabel -rw /dev/rvn0 fd${MFS_SIZE} || fail $? disklabel
     else
-	cp ${BUILDDIR}/../floppy.tree/etc/mfs.login.conf /mnt/etc/login.conf
+	disklabel -rw vn0 auto || fail $? disklabel
     fi
-    cat lang/README.${LANGUAGE} | sed -e "s/@VER@/${VER}/g" > /mnt/README
-fi
-cp lang/update.${LANGUAGE} /mnt/stand/update
-if [ "${TYPE}" = "dial" ] ; then
-    for i in reboot login dialup; do
-	cp lang/${i}.${LANGUAGE} /mnt/stand/${i}
-    done
-    ln -f /mnt/stand/reboot /mnt/stand/shutdown
-    (cd ../help;\
-    rm -rf tmp_hlp;\
-    mkdir tmp_hlp;\
-    for i in `ls *.hlp.${LANGUAGE}`; do \
+
+    newfs -i ${MFS_INODES} -m 0 -p 0 -o space /dev/rvn0c
+    mount /dev/vn0c ${MFS_MOUNTPOINT} || fail $? no_mount
+
+    pwd=`pwd`
+}
+
+populate_mfs() {
+    echo "-> Populating MFS tree..."
+    cd ../${TYPE}
+    make -f Makefile.mfs DESTDIR=${MFS_MOUNTPOINT} > /dev/null || \
+	fail $? mtree
+    if [ X"${NO_DEVFS}" != X"" ] ; then
+	make -f Makefile.mfs DESTDIR=${MFS_MOUNTPOINT} devnodes \
+		> /dev/null || fail $? makedevs
+    fi
+
+    MFS_RC=floppy.tree/etc/mfs.rc
+    if [ ! -f ${MFS_RC} ] ; then # no private version. use generic mfs.rc
+	MFS_RC=${BUILDDIR}/../${MFS_RC}
+    fi
+    if [ "${INIT}" = "oinit" ] ; then
+	cat ${MFS_RC} | sed -e "s/@VER@/${VER}/g" > ${MFS_MOUNTPOINT}/etc/oinit.rc
+    else
+	cat ${MFS_RC} | sed -e "s/@VER@/${VER}/g" > ${MFS_MOUNTPOINT}/etc/rc
+	if [ -f floppy.tree/etc/mfs.login.conf ] ; then
+	    cp floppy.tree/etc/mfs.login.conf ${MFS_MOUNTPOINT}/etc/login.conf
+	else
+	    cp ${BUILDDIR}/../floppy.tree/etc/mfs.login.conf \
+			${MFS_MOUNTPOINT}/etc/login.conf
+	fi
+    fi
+
+    if [ "${TYPE}" = "dial" ] ; then
+	for i in login dialup; do
+	    cp lang/${i}.${LANGUAGE} ${MFS_MOUNTPOINT}/stand/${i}
+	done
+	ln -s /stand/reboot ${MFS_MOUNTPOINT}/stand/shutdown
+	(cd ../help;\
+	rm -rf tmp_hlp;\
+	mkdir tmp_hlp;\
+	for i in `ls *.hlp.${LANGUAGE}`; do \
 	    cp $i tmp_hlp/`basename $i .hlp.${LANGUAGE}`;\
-    done;\
-    cd tmp_hlp;\
-    ar -cru help.a *;\
-    cp help.a /mnt/help.a)
-fi
+	done;\
+	cd tmp_hlp;\
+	ar -cru help.a *;\
+	cp help.a ${MFS_MOUNTPOINT}/help.a)
+    fi
 
-echo "-> Making and installing crunch1..."
-cd crunch1
-make "SRC=${SRC}" && make install 2>&1 >/dev/null || fail $? crunch
+    echo "-> Making and installing crunch1..."
+    cd crunch1
+    make -f ../../build/Makefile.crunch "SRC=${SRC}" && \
+	make -f ../../build/Makefile.crunch install 2>&1 >/dev/null || \
+	fail $? crunch
 
-cd ${pwd}
+    cd ${pwd}
+    if [ -f ${MFS_MOUNTPOINT}/stand/sshd ] ; then
+	echo "creating host key for sshd"
+	ssh-keygen1 -f ${MFS_MOUNTPOINT}/etc/ssh_host_key -N "" -C "root@picobsd"
+    fi
 
-(echo "-> Fixing permissions"; cd /mnt; chown -R root *)
+    (echo "-> Fixing permissions"; cd ${MFS_MOUNTPOINT}; chown -R root *)
+    df -ik ${MFS_MOUNTPOINT}
+    umount ${MFS_MOUNTPOINT}
+    fsck -p /dev/rvn0c
+    vnconfig -u /dev/rvn0
+}
 
 # stage2
 
-echo "-> Preparing kernel..."
-cp -p ${SRC}/sys/compile/PICOBSD${suffix}/kernel kernel || \
+do_kernel() {
+    echo "-> Preparing kernel..."
+    (cd ../${TYPE}; make -v -f ${BUILDDIR}/Makefile.conf )
+    cp -p ${SRC}/sys/compile/PICOBSD${suffix}/kernel kernel || \
 	fail $? missing_kernel
+    strip kernel
+    strip --remove-section=.note --remove-section=.comment kernel
+    gzip -9 -v -n kernel
+}
 
-echo "-> Preparing kernel with MFS filesystem inside..."
-df -ik /mnt
-umount /mnt
-fsck -p /dev/rvn0c
-vnconfig -u /dev/rvn0
+do_floppy() {
+    # On entry we are in /usr/src/release/build.
 
-strip kernel
-strip --remove-section=.note --remove-section=.comment kernel
-gzip -9 -v -n kernel
+    echo "==> Preparing ${FLOPPY_SIZE}kB floppy filesystem..."
 
-#---- stage3
+    dd of=picobsd.bin if=/dev/zero count=${FLOPPY_SIZE} bs=1k
 
-# stage3 -- prepare floppy filesystem and image.
-# by default we are in /usr/src/release/build
-#
-
-echo "-> Preparing ${FLOPPY_SIZE}kB floppy filesystem..."
-umount /dev/vn0 2> /dev/null || true
-umount /mnt 2> /dev/null || true
-vnconfig -u /dev/rvn0 2> /dev/null || true
-
-dd of=picobsd.bin if=/dev/zero count=${FLOPPY_SIZE} bs=1k
-
-awk 'BEGIN {printf "%c%c", 85, 170}' | \
+    awk 'BEGIN {printf "%c%c", 85, 170}' | \
                 dd of=picobsd.bin obs=1 seek=510 conv=notrunc  2> /dev/null
 
-#vnconfig -s labels -c /dev/rvn0 picobsd.bin 2>/dev/null
-vnconfig -c /dev/rvn0 picobsd.bin || fail $? vnconfig2
+    vnconfig -c /dev/rvn0 picobsd.bin || fail $? vnconfig2
 
-dd if=/boot/boot1 of=picobsd.bin conv=notrunc 2> /dev/null
+    dd if=/boot/boot1 of=picobsd.bin conv=notrunc 2> /dev/null
 
-# XXX todo: right floppy size!
-disklabel -Brw -b /boot/boot1 -s /boot/boot2 /dev/rvn0 fd1440 || \
+    # XXX todo: use a type matching floppy size.
+    disklabel -Brw -b /boot/boot1 -s /boot/boot2 /dev/rvn0 fd1440 || \
 	fail $?  disklabel
 
-newfs -i ${FLOPPY_INODES} -m 0 -p 0 -o space /dev/rvn0c
+    newfs -i ${FLOPPY_INODES} -m 0 -p 0 -o space /dev/rvn0c
 
-mount /dev/vn0c /mnt
+    mount /dev/vn0c ${MFS_MOUNTPOINT}
 
-echo "-> Populating floppy filesystem..."
+    echo "==> Populating floppy filesystem..."
 
-### copy floppy tree excluding private files.
-excl=${BUILDDIR}/../${TYPE}/floppy.tree.exclude
-if [ -f ${excl} ] ; then
-    excl="--exclude-from ${excl}"
-    echo "Exclude following files from ${excl}:\n==="
-    cat ${excl}
-    echo "==="
-else
-    excl=""
-fi
-(cd ${BUILDDIR}/../floppy.tree ; tar -cf - ${excl} . ) | (cd /mnt ; tar xvf - )
+    # Configuration files are first copied to a local tree, then
+    # compressed, then transferred back to the floppy.
+    rm -rf floppy.tree || true
+    mkdir floppy.tree
 
-if [ -d ${BUILDDIR}/../${TYPE}/floppy.tree ] ; then
-    echo "-> update with private files:"
-    (cd ${BUILDDIR}/../${TYPE}/floppy.tree ; tar cf - . ) | (cd /mnt ; tar xvf - )
-fi
+    excl=${BUILDDIR}/../${TYPE}/floppy.tree.exclude
+    if [ -f ${excl} ] ; then
+	excl="--exclude-from ${excl}"
+	echo "Exclude following files from ${excl}:\n==="
+	cat ${excl}
+	echo "==="
+    else
+	excl=""
+    fi
+    (cd ${BUILDDIR}/../floppy.tree ; tar -cf - ${excl} . ) | \
+		(cd floppy.tree ; tar xvf - )
 
-files="hosts motd"
-echo "-> Copying language dependent files: ${files} -> /mnt/etc ..."
-for i in ${files} ; do
+    if [ -d ${BUILDDIR}/../${TYPE}/floppy.tree ] ; then
+	echo "-> update with private files:"
+	(cd ${BUILDDIR}/../${TYPE}/floppy.tree ; tar cf - . ) | \
+	    (cd floppy.tree ; tar xvf - )
+    fi
+    if [ -d ${BUILDDIR}/../${TYPE}/floppy.tree.${SITE} ] ; then
+	echo "-> update with site-specific (${SITE}) files:"
+	(cd ${BUILDDIR}/../${TYPE}/floppy.tree.${SITE} ; tar cf - . ) | \
+	    (cd floppy.tree ; tar xvf - )
+    fi
+    rm -f floppy.tree/etc/mfs\.*  # mfs.rc, mfs.login.conf
+    files="motd"
+    echo "-> Copying language dependent files: ${files} -> /mnt/etc ..."
+    for i in ${files} ; do
 	cat ${BUILDDIR}/../${TYPE}/lang/${i}.${LANGUAGE} | \
-		sed -e "s/@VER@/${VER}/g" > /mnt/etc/${i}
-done
+		sed -e "s/@VER@/${VER}/g" > floppy.tree/etc/${i}
+    done
 
-if [ "${TYPE}" = "dial" ] ; then
-    cp -p /mnt/etc/master.passwd .
-    pwd_mkdb -d . master.passwd
-    mv spwd.db /mnt/etc/
-    rm pwd.db master.passwd
-fi
+    # XXX check this! i am unsure how it is necessary.
+    if [ "${TYPE}" = "dial" ] ; then
+	cp -p floppy.tree/etc/master.passwd .
+	pwd_mkdb -d . master.passwd
+	mv spwd.db floppy.tree/etc/
+	rm pwd.db master.passwd
+    fi
+    # gzip returns an error if it fails to compress some file
+    gzip -9 floppy.tree/etc/* || true
 
-cp kernel.gz /mnt/kernel.gz || fail $? kernel_compress
+    # Now, first copy large files, then small ones.
+    cp -p kernel.gz ${MFS_MOUNTPOINT}/kernel.gz || fail $? kernel_compress
 
-gzip -9cv ${MFS_NAME} > /mnt/${MFS_NAME}.gz || fail $? mfs_compress
+    gzip -9cv ${MFS_NAME} > ${MFS_MOUNTPOINT}/${MFS_NAME}.gz || \
+		fail $? mfs_compress
 
-if [ ! -d /mnt/boot/defaults ] ; then
-    mkdir -p /mnt/boot/defaults
-fi
-cp /boot/loader .
-# Make sure we have the a.out stubs we need...
-# This is deprecated for 3.X
-if [ ! -f /usr/lib/aout/kzhead.o ] ; then
-	(cd ${SRC}/sys/i386/boot/kzipboot && make all install clean)
-fi
-/usr/bin/kzip -v loader
-mv loader.kz /mnt/boot/loader
-rm -f loader loader.o
-# XXX is next line ok ?
-echo "/boot/loader" >/mnt/boot.config
-cp ${SRC}/sys/boot/forth/loader.4th /mnt/boot/
-cp ${SRC}/sys/boot/forth/support.4th /mnt/boot/
-cp ${SRC}/sys/boot/forth/loader.conf /mnt/boot/defaults
-echo "userconfig_script_load=\"YES\""	>/mnt/boot/loader.conf
-echo "rootfs_load=\"YES\""		>>/mnt/boot/loader.conf
-echo "rootfs_name=\"${MFS_NAME}\""	>>/mnt/boot/loader.conf
-echo "rootfs_type=\"mfs_root\""		>>/mnt/boot/loader.conf
-for i in frames screen ; do
-	cp ${SRC}/share/examples/bootforth/${i}.4th /mnt/boot/
-done
-cp ../forth/loader.rc /mnt/boot/loader.rc
-cp ../forth/menu.4th /mnt/boot/menu.4th
-(echo "-> Fixing permissions"; cd /mnt; chown -R root *)
+    if [ ! -d ${MFS_MOUNTPOINT}/boot ] ; then
+	mkdir -p ${MFS_MOUNTPOINT}/boot
+    fi
+    #
+    # make small loader
+    #(cd /usr/src/sys/boot/i386/loader ; make clean ;
+    # cd /usr/src/sys/boot/i386 ; make -DNOFORTH )
+    if [ -f /usr/src/sys/boot/i386/loader/loader ]; then
+	theloader=/usr/src/sys/boot/i386/loader/loader
+    else
+	theloader=/boot/loader
+    fi
+    kgzip -o loader $theloader
+    cp -p loader ${MFS_MOUNTPOINT}/boot/loader
 
-df -ik /mnt
-umount /mnt
-vnconfig -u /dev/rvn0
-rm kernel.gz ${MFS_NAME}
+    #
+    # now transfer the floppy tree
+    cp -Rp floppy.tree/* ${MFS_MOUNTPOINT}
+    cat <<__EOF > ${MFS_MOUNTPOINT}/boot/loader.rc
+load kernel
+load -t mfs_root ${MFS_NAME}
+__EOF
+    (echo "-> Fixing permissions"; cd ${MFS_MOUNTPOINT} ; chown -R root *)
+
+    df -ik ${MFS_MOUNTPOINT} > .build.reply
+    umount ${MFS_MOUNTPOINT}
+    vnconfig -u /dev/rvn0
+    # rm kernel.gz ${MFS_NAME}
+}
+
+do_kernel
+create_mfs
+populate_mfs
+do_floppy
