MFC: cleanup in PicoBSD scripts, bump version to 0.445

diff --git a/release/picobsd/build/stage1 b/release/picobsd/build/stage1
--- a/release/picobsd/build/stage1
+++ b/release/picobsd/build/stage1
@@ -1,6 +1,6 @@
 #! /bin/sh -
 
-#	$Id$
+#	$Id: stage1,v 1.10 1999/08/23 08:33:08 luigi Exp $
 #
 # stage1 -- this script fills the mfs for the picobsd kernel
 
@@ -8,8 +8,9 @@
 
 set -e	# abort in case of untested errors
 
+MFS_NAME=fs.PICOBSD
 # fail errno errcode
-# is the function used to trap errors and print msgs
+# This function is used to trap errors and print msgs
 #
 fail() {
     errno=$1
@@ -17,14 +18,14 @@ fail() {
     echo "--> Error $errno code $errcode"
     case $errcode in
     no_vnconfig)
-	echo "Error while doing vnconfig of fs.PICOBSD on /dev/rvn0..."
+	echo "Error while doing vnconfig of ${MFS_NAME} on /dev/rvn0..."
 	echo "   Most probably your running kernel doesn't have the vn(4) device."
 	;;
     disklabel)
-	echo "Error while labeling fs.PICOBSD size $SIZE"
+	echo "Error while labeling ${MFS_NAME} size $SIZE"
 	;;
     no_mount)
-	echo "Error while mounting fs.PICOBSD (/dev/vn0c) on /mnt"
+	echo "Error while mounting ${MFS_NAME} (/dev/vn0c) on /mnt"
 	;;
     mtree)
 	echo "Error while making hierarchy in /mnt"
@@ -41,25 +42,33 @@ fail() {
     disklabel)
 	echo "Error while doing disklabel on of floppy.img size $FLOPPY_SIZE"
 	;;
+    kernel_compress)
+	echo "Error while copying compressed kernel to disk"
+	;;
+    mfs_compress)
+	echo "Error while copying compressed mfs image to disk"
+	;;
+    missing_kernel)
+	echo "-> ERROR: you must build PICOBSD${suffix} kernel first"
+	;;
     esac
     echo "-> Aborting $0"
     exit 10
 }
-
 
 echo "-> Preparing MFS filesystem..."
 umount /dev/vn0 2> /dev/null || true
 umount /mnt 2> /dev/null || true
 vnconfig -u /dev/rvn0 2> /dev/null || true
 
-dd of=fs.PICOBSD if=/dev/zero count=${SIZE} bs=1k 2> /dev/null
+dd of=${MFS_NAME} if=/dev/zero count=${SIZE} bs=1k 2> /dev/null
 
 awk 'BEGIN {printf "%c%c", 85, 170}' | \
-    dd of=fs.PICOBSD obs=1 seek=510 conv=notrunc  2> /dev/null
+    dd of=${MFS_NAME} obs=1 seek=510 conv=notrunc  2> /dev/null
 
-vnconfig -s labels -c /dev/rvn0 fs.PICOBSD 2>/dev/null || fail $? no_vnconfig
+vnconfig -s labels -c /dev/rvn0 ${MFS_NAME} 2>/dev/null || fail $? no_vnconfig
 
-dd if=/boot/boot1 of=fs.PICOBSD conv=notrunc 2> /dev/null
+dd if=/boot/boot1 of=${MFS_NAME} conv=notrunc 2> /dev/null
 
 # This command does weird things on 2.2.x systems.
 # For small image sizes, use std disktypes
@@ -69,7 +78,7 @@ else
 	disklabel -rw vn0 auto || fail $? disklabel
 fi
 
-newfs -i ${MFS_INODES} -m 0 -p 0 -o space /dev/rvn0c 2>&1 >/dev/null
+newfs -i ${MFS_INODES} -m 0 -p 0 -o space /dev/rvn0c
 mount /dev/vn0c /mnt || fail $? no_mount
 
 pwd=`pwd`
@@ -78,15 +87,12 @@ echo "-> Populating MFS tree..."
 cd ../${TYPE}
 make -f Makefile.mfs || fail $? mtree
 if [ X"${NO_DEVFS}" != X"" ] ; then
-	make -f Makefile.mfs devnodes || fail $? makedevs
+    make -f Makefile.mfs devnodes || fail $? makedevs
 fi
 
-# MY_ETC contains files which override the global config in DEFAULT_ETC
-
-if [ -f floppy.tree/etc/mfs.rc ] ; then
-    MFS_RC=floppy.tree/etc/mfs.rc
-else
-    MFS_RC=../floppy.tree/etc/mfs.rc
+MFS_RC=floppy.tree/etc/mfs.rc
+if [ ! -f ${MFS_RC} ] ; then # no private version. use generic mfs.rc
+    MFS_RC=../${MFS_RC}
 fi
 if [ "${INIT}" = "oinit" ] ; then
     cat ${MFS_RC} | sed -e "s/@VER@/${VER}/g" > /mnt/etc/oinit.rc
@@ -126,37 +132,19 @@ cd ${pwd}
 
 # stage2
 
-#if [ ! -f ${SRC}/sys/compile/PICOBSD${suffix}.${SIZE}/kernel ]; then
-#    echo "-> ERROR: you must build PICOBSD${suffix}.${SIZE} first"
-#    exit 1
-#fi
-if [ ! -f ${SRC}/sys/compile/PICOBSD${suffix}/kernel ]; then
-    echo "-> ERROR: you must build PICOBSD${suffix} first"
-    exit 1
-fi
-
 echo "-> Preparing kernel..."
-cp -p ${SRC}/sys/compile/PICOBSD${suffix}/kernel kernel
-if [ ! -f kernel ]; then
-	echo "-> ERROR: you must build PICOBSD${suffix} kernel first"
-	exit 1
-fi
+cp -p ${SRC}/sys/compile/PICOBSD${suffix}/kernel kernel || \
+	fail $? missing_kernel
 
 echo "-> Preparing kernel with MFS filesystem inside..."
 df -ik /mnt
-umount /mnt 2>&1 >/dev/null
+umount /mnt
 fsck -p /dev/rvn0c
-vnconfig -u /dev/rvn0 2>&1 >/dev/null
+vnconfig -u /dev/rvn0
 
-#if [ ! -f ../tools/write_mfs_in_kernel/wmik ]; then
-#	(cd ../tools/write_mfs_in_kernel; make)
-#fi
-
-#../tools/write_mfs_in_kernel/wmik kernel fs.PICOBSD
 strip kernel
 strip --remove-section=.note --remove-section=.comment kernel
-gzip -9 -n kernel
-#rm fs.PICOBSD
+gzip -9 -v -n kernel
 
 #---- stage3
 
@@ -164,77 +152,65 @@ gzip -9 -n kernel
 # by default we are in /usr/src/release/build
 #
 
-if [ ! -f kernel.gz ]; then
-	echo "-> ERROR: you must build kernel.gz first"
-	exit 1
-fi
-
 echo "-> Preparing ${FLOPPY_SIZE}kB floppy filesystem..."
 umount /dev/vn0 2> /dev/null || true
 umount /mnt 2> /dev/null || true
 vnconfig -u /dev/rvn0 2> /dev/null || true
 
-dd of=picobsd.bin if=/dev/zero count=${FLOPPY_SIZE} bs=1k 2> /dev/null
+dd of=picobsd.bin if=/dev/zero count=${FLOPPY_SIZE} bs=1k
 
 awk 'BEGIN {printf "%c%c", 85, 170}' | \
                 dd of=picobsd.bin obs=1 seek=510 conv=notrunc  2> /dev/null
 
 #vnconfig -s labels -c /dev/rvn0 picobsd.bin 2>/dev/null
-vnconfig -c /dev/rvn0 picobsd.bin 2>/dev/null || fail $? vnconfig2
+vnconfig -c /dev/rvn0 picobsd.bin || fail $? vnconfig2
 
 dd if=/boot/boot1 of=picobsd.bin conv=notrunc 2> /dev/null
 
 # XXX todo: right floppy size!
-disklabel -Brw -b /boot/boot1 -s /boot/boot2 /dev/rvn0 fd1440 2>&1 >/dev/null || fail $?  disklabel
+disklabel -Brw -b /boot/boot1 -s /boot/boot2 /dev/rvn0 fd1440 || \
+	fail $?  disklabel
 
-newfs -i ${FLOPPY_INODES} -m 0 -p 0 -o space /dev/rvn0c 2>&1 >/dev/null
+newfs -i ${FLOPPY_INODES} -m 0 -p 0 -o space /dev/rvn0c
 
 mount /dev/vn0c /mnt
 
-echo "-> `pwd`: Populating floppy filesystem..."
+echo "-> Populating floppy filesystem..."
 
-# copy floppy tree excluding private files.
-(cd ../floppy.tree ; \
-    tar -cvf - --exclude-from ../${TYPE}/floppy.tree.exclude . ) | \
-    (cd /mnt ; tar xvf - )
+### copy floppy tree excluding private files.
+excl=../${TYPE}/floppy.tree.exclude
+if [ -f ${excl} ] ; then
+    excl="--exclude-from ${excl}"
+    echo "Exclude following files from ${excl}:\n==="
+    cat ${excl}
+    echo "===
+else
+    excl=""
+fi
+(cd ../floppy.tree ; tar -cf - ${excl} . ) | (cd /mnt ; tar xvf - )
 
-# update with private files
 if [ -d ../${TYPE}/floppy.tree ] ; then
-    (cd ../${TYPE}/floppy.tree ; tar cvf - . ) | (cd /mnt ; tar xvf - )
+    echo "-> update with private files:"
+    (cd ../${TYPE}/floppy.tree ; tar cf - . ) | (cd /mnt ; tar xvf - )
 fi
 
-echo "-> `pwd`: Copying language dependent files..."
-for i in hosts motd ; do
+files="hosts motd"
+echo "-> Copying language dependent files: ${files} -> /mnt/etc ..."
+for i in ${files} ; do
 	cat ../${TYPE}/lang/${i}.${LANGUAGE} | \
 		sed -e "s/@VER@/${VER}/g" > /mnt/etc/${i}
 done
 
 if [ "${TYPE}" = "dial" ] ; then
-	cp -p /mnt/etc/master.passwd .
-	pwd_mkdb -d . master.passwd
-	mv spwd.db /mnt/etc/
-	rm pwd.db master.passwd
+    cp -p /mnt/etc/master.passwd .
+    pwd_mkdb -d . master.passwd
+    mv spwd.db /mnt/etc/
+    rm pwd.db master.passwd
 fi
 
-if [ "X$?" != "X0" ] ; then
-	echo "-> ERROR while transferring ../${TYPE}/floppy.tree to /mnt..."
-	echo "-> Aborting $0"
-	exit 10
-fi
+cp kernel.gz /mnt/kernel.gz || fail $? kernel_compress
 
-cp kernel.gz /mnt/kernel.gz
-if [ "X$?" != "X0" ] ; then
-	echo "-> ERROR while transferring kernel.gz to /mnt..."
-	echo "-> Aborting $0"
-	exit 10
-fi
-
-gzip -9cv fs.PICOBSD > /mnt/fs.PICOBSD.gz
-if [ "X$?" != "X0" ] ; then
-	echo "\-> ERROR transferring MFS to /mnt"
-	echo "-> Aborting $0"
-	exit 10
-fi
+gzip -9cv ${MFS_NAME} > /mnt/${MFS_NAME}.gz || fail $? mfs_compress
 
 mkdir /mnt/boot
 mkdir /mnt/boot/defaults
@@ -252,20 +228,18 @@ echo "/boot/loader" >/mnt/boot.config
 cp ${SRC}/sys/boot/forth/loader.4th /mnt/boot/
 cp ${SRC}/sys/boot/forth/support.4th /mnt/boot/
 cp ${SRC}/sys/boot/forth/loader.conf /mnt/boot/defaults
-echo "userconfig_script_load=\"YES\"">/mnt/boot/loader.conf
-echo "rootfs_load=\"YES\"" >>/mnt/boot/loader.conf
-echo "rootfs_name=\"fs.PICOBSD\"" >>/mnt/boot/loader.conf
-echo "rootfs_type=\"mfs_root\"" >>/mnt/boot/loader.conf
-for i in frames screen
-do
+echo "userconfig_script_load=\"YES\""	>/mnt/boot/loader.conf
+echo "rootfs_load=\"YES\""		>>/mnt/boot/loader.conf
+echo "rootfs_name=\"${MFS_NAME}\""	>>/mnt/boot/loader.conf
+echo "rootfs_type=\"mfs_root\""		>>/mnt/boot/loader.conf
+for i in frames screen ; do
 	cp ${SRC}/share/examples/bootforth/${i}.4th /mnt/boot/
 done
 cp ../forth/loader.rc /mnt/boot/loader.rc
 cp ../forth/menu.4th /mnt/boot/menu.4th
 (echo "-> Fixing permissions"; cd /mnt; chown -R root *)
-rm kernel.gz
 
 df -ik /mnt
-
 umount /mnt
 vnconfig -u /dev/rvn0
+rm kernel.gz ${MFS_NAME}
