Enable support for Lucifer's floppies. More stylistic drick-drack in bininst.
git-svn-id: svn+ssh://svn.freebsd.org/base/head@4340 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f

diff --git a/release/bininst b/release/bininst
--- a/release/bininst
+++ b/release/bininst
@@ -13,7 +13,7 @@
 # your name on top after doing something trivial like reindenting it, just
 # to make it look like you wrote it!).
 #
-# $Id: bininst,v 1.22 1994/11/09 20:16:09 jkh Exp $
+# $Id: bininst,v 1.23 1994/11/09 23:02:11 jkh Exp $
 
 # Some useful constants.
 PATH=/usr/bin:/usr/sbin:/bin:/sbin:/stand
@@ -100,19 +100,24 @@ network_dialog()
 
 # Print welcome banner.
 welcome() {
-	dialog --title "Welcome to FreeBSD" $clear \
+	dialog --title "Welcome to FreeBSD!" $clear \
 --msgbox " We're now ready to install one or more packed distribution
 sets onto your machine.  At the minimum, you need a bindist
 distribution, though a secrdist is also useful if you want your
 system to use the same DES and/or Kerberos security model used
 by other commercial systems (the FreeBSD model is md5 based,
 and not bad in and of itself though).  The secrdist is also a
-bit of a special case since it cannot be legally obtained from
-the U.S. due to export restrictions, but non-U.S. versions are
-also available.  See the release notes for more information on
-obtaining a secrdist for your part of the world.  If you're
-interested in doing FreeBSD development, a srcdist is also
-highly recommended!" 18 72
+bit of a special case since it cannot be legally obtained via
+U.S. ftp sites from outside the U.S. due to export restrictions,
+but non-U.S. versions are also available.  See the release notes
+for more information on obtaining a secrdist for your part of the
+world.  If you wish to run a 1.x binary (and can't simply recompile
+it from source), it's also recommended that you install the
+compat1xdist.  If you're interested in doing FreeBSD development,
+a srcdist is also very highly recommended!  Finally, many useful
+pre-compiled packages are available and may be obtained from:
+
+	ftp://ftp.freebsd.org/pub/FreeBSD/2.0-ALPHA/packages" 22 72
 	if ! handle_rval $?; then return 1; fi
 }
 
@@ -309,11 +314,11 @@ setup_network_plip()
 setup_network()
 {
 	done=0
-	clear="--clear"
 	while [ "$interface" = "" ]; do
+		clear="--clear"
 		dialog $clear --title "Set up network interface" \
 		--menu "Please select the type of network connection you have:\n\n" \
-		20 72 3 \
+		15 72 3 \
 		"ether" "A supported ethernet card" \
 		"SLIP" "A point-to-point SLIP (Serial Line IP) connection" \
 		"PLIP" "A Parallel-Line IP setup (sort of like lap-link)" \
@@ -325,78 +330,76 @@ setup_network()
 		if ! handle_rval $retval; then return 1; fi
 		case $choice in
 		ether)
-		if ! setup_network_ether; then continue; fi
-	;;
+			if ! setup_network_ether; then continue; fi
+		;;
 
-	SLIP)
-		if ! setup_network_slip; then continue; fi
-	;;
+		SLIP)
+			if ! setup_network_slip; then continue; fi
+		;;
 
-	PLIP)
-		if ! setup_network_plip; then continue; fi
-	;;
-	esac	
-	if [ "$interface" = "" ]; then	continue; fi
+		PLIP)
+			if ! setup_network_plip; then continue; fi
+		;;
+		esac	
+		if [ "$interface" = "" ]; then	continue; fi
 
-	clear=""
-	default_value=""
-	if ! network_dialog "What is the fully qualified name of this host"; then return 1; fi
-	hostname=$answer
-	echo $hostname > /etc/myname
-	hostname $hostname
+		clear=""
+		default_value=""
+		if ! network_dialog "What is the fully qualified name of this host"; then clear="--clear"; return 1; fi
+		hostname=$answer
+		echo $hostname > /etc/myname
+		hostname $hostname
 
-	default_value=`echo $hostname | sed -e 's/[^.]*\.//'`
-	if network_dialog "What is the domain name of this host (Internet, not YP/NIS)"; then
-		domain=$answer
-	fi
-
-	default_value=""
-	if ! network_dialog "What is the IP address of this host"; then clear="--clear"; return 1; fi
-	ipaddr=$answer
-
-        echo "$ipaddr    $hostname `echo $hostname | sed -e s/\.$domain//`" \
-             >> /etc/hosts
-
-	default_value="$netmask"
-	if network_dialog "Please specify the netmask"; then
-		if [ "$answer" != "" ]; then
-			netmask=$answer
+		default_value=`echo $hostname | sed -e 's/[^.]*\.//'`
+		if network_dialog "What is the domain name of this host (Internet, not YP/NIS)"; then
+			domain=$answer
 		fi
-	fi
 
-	default_value=""
-	if network_dialog "Any extra flags to ifconfig?" ; then
-		ifconfig_flags=$answer
-	fi
-	echo "Progress <$IFCONFIG $interface $ipaddr $remote_hostip netmask $netmask $ifconfig_flags>" >/dev/ttyv1
-	if ! $IFCONFIG $interface $ipaddr $remote_hostip netmask $netmask $ifconfig_flags > /dev/ttyv1 2>&1 ; then
-		error "Unable to configure interface $interface"
-		ipaddr=""; interface=""
-		continue
-	fi
-	if [ "$interface" = "sl0" ]; then
-		slattach -a -s $serial_speed $serial_interface
-	fi
-	rm -f ${TMP}/inputbox.tmp.$$
-	echo "$ipaddr $remote_hostip netmask $netmask $ifconfig_flags" > /etc/hostname.$interface
-	default_value=""
-	if network_dialog "If you have a default gateway, enter its IP address (otherwise cancel)"; then
-		if [ "$answer" != "" ]; then
-			gateway=$answer
-			echo "Progress <$ROUTE $ROUTE_FLAGS $gateway>" > /dev/ttyv1 2>&1
-			$ROUTE $ROUTE_FLAGS $gateway > /dev/ttyv1 2>&1
-		fi
-	fi
+		default_value=""
+		if ! network_dialog "What is the IP address of this host"; then clear="--clear"; return 1; fi
+		ipaddr=$answer
 
-	default_value=""
-	if network_dialog "If you have a name server, enter its IP address (otherwise cancel)"; then
-		if [ "$answer" != "" ]; then
-			nameserver=$answer
-			echo "nameserver $nameserver" > /etc/resolv.conf
+        	echo "$ipaddr    $hostname `echo $hostname | sed -e 's/\.$domain//'`" >> /etc/hosts
+
+		default_value="$netmask"
+		if network_dialog "Please specify the netmask"; then
+			if [ "$answer" != "" ]; then
+				netmask=$answer
+			fi
 		fi
-	fi
+
+		default_value=""
+		if network_dialog "Any extra flags to ifconfig?" ; then
+			ifconfig_flags=$answer
+		fi
+		echo "Progress <$IFCONFIG $interface $ipaddr $remote_hostip netmask $netmask $ifconfig_flags>" >/dev/ttyv1
+		if ! $IFCONFIG $interface $ipaddr $remote_hostip netmask $netmask $ifconfig_flags > /dev/ttyv1 2>&1 ; then
+			error "Unable to configure interface $interface"
+			ipaddr=""; interface=""
+			continue
+		fi
+		if [ "$interface" = "sl0" ]; then
+			slattach -a -s $serial_speed $serial_interface
+		fi
+		rm -f ${TMP}/inputbox.tmp.$$
+		echo "$ipaddr $remote_hostip netmask $netmask $ifconfig_flags" > /etc/hostname.$interface
+		default_value=""
+		if network_dialog "If you have a default gateway, enter its IP address"; then
+			if [ "$answer" != "" ]; then
+				gateway=$answer
+				echo "Progress <$ROUTE $ROUTE_FLAGS $gateway>" > /dev/ttyv1 2>&1
+				$ROUTE $ROUTE_FLAGS $gateway > /dev/ttyv1 2>&1
+			fi
+		fi
+
+		default_value=""
+		if network_dialog "If you have a name server, enter its IP address"; then
+			if [ "$answer" != "" ]; then
+				nameserver=$answer
+				echo "nameserver $nameserver" > /etc/resolv.conf
+			fi
+		fi
 	done
-	clear="--clear"
 }
 
 extract_dist()
