Convert "RELENG_ver_RELEASE" to "RELEASE_ver" and use it to check out the ports and doc trees.  There is no change if we are not building a release (i.e., we are not using a tag of the form RELENG_ver_RELEASE --e.g., a RELENG_ver tag used to build a snapshot).
This should allow the ports and doc freezes during the release cycles
to be somewhat shorter, as commits to those (non-branched) trees can
resume as soon as the tags are laid down.

Reviewed by:	nik
Approved by:	jkh

diff --git a/release/Makefile b/release/Makefile
--- a/release/Makefile
+++ b/release/Makefile
@@ -24,6 +24,17 @@ BUILDNAME?=${BASE}-${DATE}-SNAP
 #CHROOTDIR=/junk/release
 # If this is a -stable snapshot, then set
 #RELEASETAG=RELENG_3
+#
+# Non-zero if ${RELEASETAG} is in the form "RELENG_ver_RELEASE"; we
+# are building an official release.  Otherwise, we are building for
+# a branch.
+.if defined(RELEASETAG)
+ISRELEASE!=	expr ${RELEASETAG} : '^RELENG_.*_RELEASE$$' || true
+.if ${ISRELEASE} != 0
+# Convert "RELENG_ver_RELEASE" to "RELEASE_ver" for ports and doc trees.
+AUXRELEASETAG!=	echo ${RELEASETAG} | sed -e 's/^RELENG_/RELEASE_/' -e 's/_RELEASE$$//'
+.endif
+.endif
 
 KERNCONF=GENERIC
 
@@ -175,10 +186,18 @@ rerelease release:
 	cd ${CHROOTDIR} && env CHROOTDIR=${CHROOTDIR} BUILDNAME=${BUILDNAME} RELEASETAG=${RELEASETAG} ${LOCAL_SCRIPT}
 .endif
 .if !defined(NOPORTS)
+.if defined(AUXRELEASETAG)
+	cd ${CHROOTDIR}/usr && rm -rf ports && cvs -R -d ${CVSROOT} co -P -r ${AUXRELEASETAG} ${RELEASEPORTSMODULE} && cd ports && make readmes PORTSDIR=${CHROOTDIR}/usr/ports
+.else
 	cd ${CHROOTDIR}/usr && rm -rf ports && cvs -R -d ${CVSROOT} co -P ${RELEASEPORTSMODULE} && cd ports && make readmes PORTSDIR=${CHROOTDIR}/usr/ports
 .endif
+.endif
 .if !defined(NODOC)
+.if defined(AUXRELEASETAG)
+	cd ${CHROOTDIR}/usr && rm -rf doc && cvs -R -d ${CVSROOT} co -P -r ${AUXRELEASETAG} ${RELEASEDOCMODULE}
+.else
 	cd ${CHROOTDIR}/usr && rm -rf doc && cvs -R -d ${CVSROOT} co -P ${RELEASEDOCMODULE}
+.endif
 	if [ -d ${DISTFILES}/ ]; then \
 		cp -rp ${DISTFILES} ${CHROOTDIR}/usr/ports/distfiles; \
 	fi
