nfsclient: Add a new nfs_client_rdma_enable variable
This patch adds a new nfs_client_rdma_enable variable
to /etc/rc.d/nfsclient to enable the client side of
NFS over RDMA.  The client side of NFS over RDMA
requires the nfsclrdma.ko module, which is still under
test/review.

I wanted to get the "glue" into main so that others
could test the module more easily.  Avaliability of
the module will be announced on freebsd-current@ soon.

It should not affect non-RDMA operation.

I've specified a long MFC, since the module still
requires extensive testing and, hopefully, a review.

MFC after:	3 months

diff --git a/libexec/rc/rc.d/nfsclient b/libexec/rc/rc.d/nfsclient
--- a/libexec/rc/rc.d/nfsclient
+++ b/libexec/rc/rc.d/nfsclient
@@ -32,6 +32,9 @@ nfsclient_start()
 			warn "failed to set vfs.nfs.bufpackets"
 		fi
 	fi
+	if checkyesno nfs_client_rdma_enable; then
+		load_kld nfsclrdma || err 1 "Cannot load nfsclrdma"
+	fi
 
 	unmount_all
 }
